Bad kubeconfig because linode cli had no token?
Error in step:

Run kubectl apply --validate=false -f k8s.yaml
error: error loading config file "./kubeconfig": couldn't get
version/kind; json parse error: json: cannot unmarshal string into Go
value of type struct { APIVersion string
"json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }